### ISSUE TITLE
Font chooser lags a lot

### ISSUE THREAD

**Issue by soumyaDghosh** [ubuntu/gnome-text-editor#18]
The font-chooser portal in the snap is kind of unusable and takes long to load.

https://github.com/ubuntu/gnome-text-editor/assets/72045785/b78276a9-35fc-4ec7-b608-3c3d26e53a95

**Comment by sergio-costas** [comment]
I compared it with the .deb version, and it seems to happen the same: trying to move the vertical scroll is glitchy. Maybe this should be reported upstream...

**Comment by soumyaDghosh** [comment]
I tried to look into the source-code... and probably this is the culprit.

https://gitlab.gnome.org/GNOME/gnome-text-editor/-/blob/main/src/editor-preferences-font.c#L74

This `GtkFontChooserDialog` is deprecated and replaced with `GtkFontDialog`.

**Comment by sergio-costas** [comment]
I see... maybe it is. Changing to GtkFontDialog seems not very complex, just creating one, calling `gtk_font_dialog_choose_font()`, and in the callback, get the `PangoFontDescription` object and use `toString`.

**Comment by soumyaDghosh** [comment]
@sergio-costas https://gitlab.gnome.org/GNOME/gnome-text-editor/-/merge_requests/141#note_1992946

this should fix the lag!

**Comment by sergio-costas** [comment]
Great! I'll prepare a patch for this. Thanks!

**Comment by sergio-costas** [comment]
I prepared a MR with that, but doesn't seem to fix the problem... Can you test it? https://github.com/ubuntu/gnome-text-editor/pull/23
